# -*- coding: utf-8 -*-
"""Cat's Food Quest.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EyriF5ccYTjNcHqcXWlV7jV5-bNTtD5U
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from IPython import display
import time
from PIL import Image
import urllib.request
import os
# %matplotlib inline

# --- 0. Automated Asset Pipeline ---
def download_assets():
    """Download game assets (Cat, Food, Water Pool) if not present."""
    assets = {
        'Cat.png': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSu3HDWpKhntZSfpUkZumxOC_lsACRcskRZ1w&s',
        'Food.png': 'https://pic.616pic.com/ys_bnew_img/00/31/77/cq8dNCY4pn.jpg',
        'Pool.png': 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTummbLnNkSL02IsJU9Ozy3DCE18tsc3ACvPQ&s'
    }
    headers = {'User-Agent': 'Mozilla/5.0'}
    for name, url in assets.items():
        if not os.path.exists(name):
            try:
                req = urllib.request.Request(url, headers=headers)
                with urllib.request.urlopen(req) as response, open(name, 'wb') as f:
                    f.write(response.read())
                print(f"Downloaded: {name}")
            except Exception as e:
                print(f"Failed to download {name}: {e}")

download_assets()

# --- 1. Q-Learning Algorithm (using string states) ---
class QLearningTable:
    """
    Q-learning agent using a pandas DataFrame as the Q-table.
    State is represented as a string (e.g., '[0,0]') to avoid indexing issues.
    """
    def __init__(self, actions, learning_rate=0.1, reward_decay=0.9, e_greedy=0.95):
        self.actions = actions
        self.lr = learning_rate
        self.gamma = reward_decay
        self.epsilon = e_greedy
        self.q_table = pd.DataFrame(columns=self.actions, dtype=np.float64)

    def choose_action(self, observation):
        """Select action using epsilon-greedy policy."""
        self.check_state_exist(observation)
        if np.random.uniform() < self.epsilon:
            # Exploit: choose the action with highest Q-value (break ties randomly)
            state_action = self.q_table.loc[observation, :]
            action = np.random.choice(state_action[state_action == np.max(state_action)].index)
        else:
            # Explore: random action
            action = np.random.choice(self.actions)
        return action

    def learn(self, s, a, r, s_):
        """Update Q-value using the Q-learning rule."""
        self.check_state_exist(s_)
        q_predict = self.q_table.loc[s, a]
        if s_ != 'terminal':
            q_target = r + self.gamma * self.q_table.loc[s_, :].max()
        else:
            q_target = r
        self.q_table.loc[s, a] += self.lr * (q_target - q_predict)

    def check_state_exist(self, state):
        """Add a new state to the Q-table if not already present (with optimistic initialization)."""
        if state not in self.q_table.index:
            # Optimistic initialization: set initial Q-values to a small positive value to encourage exploration
            new_state = pd.DataFrame([[5.0] * len(self.actions)],
                                     index=[state],
                                     columns=self.q_table.columns)
            self.q_table = pd.concat([self.q_table, new_state])

# --- 2. Game Environment (fixed cat, food, and fixed water pits) ---
class ColabCatMaze:
    """
    A 6x6 grid world where a cat (fixed at [0,0]) must find food (fixed at [5,5])
    while avoiding fixed water pits at [[1,3], [2,2], [3,4], [4,1]].
    Features:
      - Fixed obstacles for stable learning.
      - Manhattan distance reward shaping to guide the agent.
      - Wall penalty for invalid moves.
      - Slowed down rendering with time.sleep(0.2) for better observation.
    State is returned as a string for compatibility with QLearningTable.
    """
    def __init__(self, size=6):
        self.size = size
        self.assets = {}
        for key in ['Cat', 'Food', 'Pool']:
            try:
                self.assets[key] = Image.open(f'{key}.png')
            except:
                self.assets[key] = None
                print(f"Warning: {key}.png could not be loaded.")
        self.victory_count = 0
        # Fixed water pits
        self.fixed_water_pits = [[1, 3], [2, 2], [3, 4], [4, 1]]
        self.reset()

    def show_welcome_screen(self):
        """Display the game rules and start message."""
        fig, ax = plt.subplots(figsize=(6, 6))
        ax.set_facecolor('#fdfdfd')
        plt.text(0.5, 0.85, "Cat's Food Quest",
                 fontsize=28, fontweight='bold', color='#2c3e50',
                 ha='center', va='center', transform=ax.transAxes)
        ax.plot([0.2, 0.8], [0.77, 0.77], color='gray', lw=1, transform=ax.transAxes)
        rules_text = (
            "GAME RULES\n"
            "---------------------------\n"
            "● Cat starts at [0,0], Food at [5,5]\n"
            "● Water pits are fixed at [1,3], [2,2], [3,4], [4,1]\n"
            "● Goal: Find Food (+10)\n"
            "● Trap: Avoid Water (-10)\n"
            "● Step Cost: -0.1\n"
            "● Wall Penalty: -1.0\n"
            "● Reward shaping encourages moving toward food.\n\n"
            "System: Initializing Environment..."
        )
        plt.text(0.5, 0.70, rules_text,
                 fontsize=14, color='#34495e',
                 ha='center', va='top',
                 linespacing=1.8, transform=ax.transAxes)
        ax.axis('off')
        display.display(plt.gcf())
        display.clear_output(wait=True)
        plt.close()
        time.sleep(2)

    def reset(self):
        """
        Reset environment:
          - Cat fixed at [0,0]
          - Food fixed at [5,5]
          - Water pits fixed to self.fixed_water_pits
        Returns state as a string.
        """
        self.cat_pos = [0, 0]
        self.food_pos = [5, 5]
        self.water_pits = self.fixed_water_pits.copy()  # use fixed pits
        return str(self.cat_pos)  # state as string

    def step(self, action):
        """
        Execute action, update environment, compute reward.
        Actions: 0=Up, 1=Down, 2=Left, 3=Right.
        Returns next_state (string), reward, done.
        """
        # Compute Manhattan distance to food before moving (for reward shaping)
        old_dist = abs(self.cat_pos[0] - self.food_pos[0]) + abs(self.cat_pos[1] - self.food_pos[1])

        # Attempt to move
        new_pos = self.cat_pos.copy()
        valid_move = True
        if action == 0 and new_pos[0] > 0:
            new_pos[0] -= 1
        elif action == 1 and new_pos[0] < self.size - 1:
            new_pos[0] += 1
        elif action == 2 and new_pos[1] > 0:
            new_pos[1] -= 1
        elif action == 3 and new_pos[1] < self.size - 1:
            new_pos[1] += 1
        else:
            valid_move = False  # tried to move out of bounds

        # Apply move if valid, otherwise stay
        if valid_move:
            self.cat_pos = new_pos
        else:
            # Wall penalty, state unchanged
            return str(self.cat_pos), -1.0, False

        # Compute new distance to food
        new_dist = abs(self.cat_pos[0] - self.food_pos[0]) + abs(self.cat_pos[1] - self.food_pos[1])

        # Base step cost
        reward = -0.1

        # Reward shaping: encourage moving toward food
        reward += (old_dist - new_dist) * 0.5  # positive if closer

        # Check terminal conditions
        if self.cat_pos == self.food_pos:
            reward += 10.0
            return str(self.cat_pos), reward, True
        if self.cat_pos in self.water_pits:
            reward -= 10.0
            return str(self.cat_pos), reward, True

        return str(self.cat_pos), reward, False

    def render(self, episode, step, total_reward):
        """Draw the current state of the maze and slow down for visibility."""
        fig, ax = plt.subplots(figsize=(5, 5))
        ax.set_xlim(0, self.size)
        ax.set_ylim(0, self.size)
        ax.set_xticks(np.arange(0, self.size + 1, 1))
        ax.set_yticks(np.arange(0, self.size + 1, 1))
        ax.grid(True, color='gray', linestyle='--', linewidth=0.5)
        ax.set_xticklabels([])
        ax.set_yticklabels([])

        # Draw water pits
        for p in self.water_pits:
            if self.assets['Pool']:
                ax.imshow(self.assets['Pool'],
                          extent=[p[1], p[1] + 1, self.size - p[0] - 1, self.size - p[0]])

        # Draw food
        if self.assets['Food']:
            ax.imshow(self.assets['Food'],
                      extent=[self.food_pos[1], self.food_pos[1] + 1,
                              self.size - self.food_pos[0] - 1, self.size - self.food_pos[0]])

        # Draw cat
        if self.assets['Cat']:
            ax.imshow(self.assets['Cat'],
                      extent=[self.cat_pos[1] + 0.1, self.cat_pos[1] + 0.9,
                              self.size - self.cat_pos[0] - 0.9, self.size - self.cat_pos[0] - 0.1])

        plt.title(f"Ep: {episode} | Step: {step} | Reward: {total_reward:.1f} | Victories: {self.victory_count}")
        display.display(plt.gcf(), display_id='game_screen', update=True)
        plt.close(fig)
        # Slow down rendering for better observation
        time.sleep(0.2)

    def show_game_over(self):
        """Display blue game over screen."""
        fig, ax = plt.subplots(figsize=(5, 5))
        ax.set_facecolor('lightskyblue')
        plt.text(0.5, 0.5, "GAME OVER", color='red', fontsize=35, fontweight='bold',
                 ha='center', transform=ax.transAxes)
        ax.axis('off')
        display.display(plt.gcf(), display_id='game_screen', update=True)
        plt.close(fig)
        time.sleep(0.4)

    def show_victory(self):
        """Display gold victory screen and increment victory counter."""
        self.victory_count += 1
        fig, ax = plt.subplots(figsize=(5, 5))
        ax.set_facecolor('gold')
        plt.text(0.5, 0.5, "VICTORY!", color='red', fontsize=35, fontweight='bold',
                 ha='center', transform=ax.transAxes)
        ax.axis('off')
        display.display(plt.gcf(), display_id='game_screen', update=True)
        plt.close(fig)
        time.sleep(0.4)

# --- 3. Training Loop & Evaluation (with step-by-step rendering) ---
env = ColabCatMaze()
env.show_welcome_screen()

# Hyperparameters
actions = [0, 1, 2, 3]
RL = QLearningTable(actions=actions, learning_rate=0.1, reward_decay=0.9, e_greedy=1.0)  # start with full exploration

step_history = []      # steps per episode
success_streak = 0
epsilon_decay = 0.995  # decay factor for epsilon
min_epsilon = 0.05     # minimum exploration rate

for episode in range(200):  # more episodes to allow convergence
    state = env.reset()
    total_reward = 0

    for step in range(50):   # max steps per episode
        # Render EVERY step to show smooth movement
        env.render(episode, step, total_reward)

        # Epsilon-greedy action selection
        action = RL.choose_action(state)

        # Take step and learn
        next_state, reward, done = env.step(action)
        RL.learn(state, action, reward, next_state)

        state = next_state
        total_reward += reward

        if done:
            # Final render already done, just show victory/over screen
            if reward >= 10:  # victory (food reward is +10, shaping may add extra)
                env.show_victory()
                success_streak += 1
            else:
                env.show_game_over()
                success_streak = 0
            step_history.append(step + 1)
            break

        if step == 49:
            # Episode ended because max steps reached
            step_history.append(50)

    # Decay epsilon (exploration rate)
    RL.epsilon = max(min_epsilon, RL.epsilon * epsilon_decay)

    # Early stopping if agent becomes stable (10 consecutive victories)
    if success_streak >= 10:
        print(f"Goal Reached! Agent stabilized at Episode {episode}")
        break

# --- 4. Visualize Progress ---
plt.figure(figsize=(10, 5))
plt.plot(step_history, marker='o', color='#3498db', label='Steps to Goal')
plt.axhline(y=10, color='r', linestyle='--', label='Shortest Possible Path')
plt.title('Agent Learning Curve: Steps taken per Episode', fontsize=16)
plt.xlabel('Episode')
plt.ylabel('Number of Steps')
plt.grid(True, alpha=0.3)
plt.legend()
plt.show()

print("Evaluation complete. A decreasing trend in the graph proves the agent is learning effectively.")